### ISSUE TITLE
github_install works with 1.13.6, not with 2.0.0, for a particular repo

### ISSUE THREAD

**Issue by MrFlick** [r-lib/devtools#1903]
I've been trying to troubleshoot a problem installing a package via `install_github`. The following command works with devtools_1.13.6, but not devtools_2.0.0 (Using R 3.5.1)

   devtools::install_github("statgen/SAIGE")

The difference is that there's a fatal error during the build. Specifically the error is

    SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory

which implies that the file is not in the tar ball. And that's true, with 2.0 I see the message

    installation of package ‘/tmp/RtmpodjtZ7/filebfa461502e93/SAIGE_0.29.4.tar.gz’ had non-zero exit status

and if I go look at that `SAIGE_0.29.4.tar.gz` tarball, I see the file is not there. I also get an error just viewing the table of contents on that file. Specifically using the `-tf` option will say

    tar: Skipping to next header
    tar: Exiting with failure status due to previous errors

So it seems the new version is making an invalid (truncated?) tarball? Is that possible? I didn't see anything in the release notes about there being differences in how tarballs might be generated between versions.

Do you have other suggestions for how to troubleshoot this? I wouldn't be surprised if this ended up being a problem with the repo rather than devtools but it's just odd it works in the other version but not the newer without a clear indication why.

This was run on Ubuntu 16.04.5 LTS and specifically commit 756bbac94144e6e92d9caf0d4a8f428c49377b17 of https://github.com/statgen/SAIGE/. Also note that some of the dependencies will write info to the user's home directory.

**Comment by jimhester** [comment]
devtools now builds packages by default before trying to install them, try installing with `build = FALSE` and see if that works.

**Comment by jimhester** [comment]
In addition the repo seems to contain a submodule, which are now checked out by default before building. If the developers do not intend for these submodules to be included in the tarball they should be added to `.Rbuildignore`.

**Comment by MrFlick** [comment]
OK. Using `build=FALSE` with devtools 2.0 does install the package without error. Thank you.

So it seems if I check the repo out via git outside of R, and run `devtools::build()` then on the repo, neither 2.0 nor 1.13 produce a working tarball (neither does `R CMD build`). So that's likely because of the sub-modules? That's very helpful info I can pass on to the maintainer. There must be something different on their machine that allows them to build successfully.
